[build-system]
requires = ["setuptools", "wheel"]

[tool.platter]
python = "python3.6"
prebuild-script = """
set -eufx
cd $SOURCE_DIR/client
yarn install --production
cd $SOURCE_DIR
pipenv install --deploy
echo "SECRET_KEY=secret" > .env
pipenv run manage.py collectstatic --noinput
"""
