[build-system]
requires = ["setuptools", "wheel"]

[tool.platter]
python = "python3.6"
prebuild-script = """
set -eufx
cd $SOURCE_DIR/client
yarn install --production
cd $SOURCE_DIR
cp setup.cfg $DATA_DIR
pipenv install --deploy
export SECRET_KEY=secret
pipenv run manage.py collectstatic --noinput
"""
