version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build
          command: docker build -t ${CIRCLE_PROJECT_REPONAME} .

      - run:
          name: Test
          command: |
               docker run --rm --detach -e POSTGRES_PASSWORD=password --name=postgres postgres:9.6-alpine
               sleep 2
               docker run --name=tests --link postgres:postgres \
                -e SECRET_KEY=s \
                -e "DATABASE_URL=postgres://postgres:password@postgres:5432/postgres" \
                ${CIRCLE_PROJECT_REPONAME} saltdash test -- --junitxml=.test-results/${CIRCLE_PROJECT_REPONAME}/junit.xml
               docker kill postgres
               docker cp tests:/srv/saltdash/.test-results test-results
               docker cp tests:/dist dist

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: dist
